apiVersion: v1
kind: Service
metadata:
    name: "zteckjob-bf03"
    labels:
        app: "zteckjob-bf03"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    selector:
        app: "zteckjob-bf03"